apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-beaver-test

resources:
  - namespace.yaml
  - dbeaver/deployment.yaml
  - dbeaver/service.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - mysql/deployment.yaml
  - mysql/service.yaml

configMapGenerator:
#DBEAVER
  - name: dbeaver-product-configmap
    files:
      - dbeaver/configs/product.conf
  - name: dbeaver-sources-user-configmap
    files:
      - dbeaver/configs/user/data-sources.json
  - name: dbeaver-sources-global-configmap
    files:
      - dbeaver/configs/global/data-sources.json
  - name: dbeaver-server-configmap
    files:
      - dbeaver/configs/cloudbeaver.conf
#POSTGRES
  - name: postgres-configmap
    literals:
    - POSTGRES_USER=my-db-user
    - POSTGRES_PASSWORD=Password123
    - POSTGRES_DB=my-postgre-db
#MYSQL
  - name: mysql-configmap
    literals:
    - MYSQL_ROOT_PASSWORD=PasswordROOT
    - MYSQL_USER=my-db-user
    - MYSQL_PASSWORD=Password123
    - MYSQL_DATABASE=my-mysql-db

secretGenerator:
#DBEAVER
- name: dbeaver-secret
  literals:
    - CB_SERVER_NAME=CloudBeaver Test Server
    - CB_ADMIN_NAME=admin.dbeaver
    - CB_ADMIN_PASSWORD=Password123

commonLabels:
  kubernetes.io/environment: dev
